# Generated by Django 2.2.3 on 2019-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_name', models.CharField(choices=[('F', 'Farmer'), ('BE', 'Beekeeper'), ('BU', 'Buyer')], default='BU', max_length=10)),
                ('department', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('role', models.CharField(choices=[(1, 'Farmer'), (2, 'Beekeeper'), (3, 'Buyer')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
